import re

def clean_math_answer(text):

    if text is None: return None
    text = str(text)
    
    unit_texts = [
    "east",
    "degree",
    "mph",
    "kmph",
    "ft",
    "m sqaure",
    " m east",
    "sq m",
    "deg",
    "mile",
    "q .",
    "monkey",
    "prime",
    "ratio",
    "profit of rs",
    "rd",
    "o",
    "gm",
    "p . m",
    "lb",
    "tile",
    "per",
    "dm",
    "lt",
    "gain",
    "ab",
    "way",
    "west",
    "a .",
    "b .",
    "c .",
    "d .",
    "e .",
    "f .",
    "g .",
    "h .",
    "t",
    "a",
    "h",
    "no change",
    "men",
    "soldier",
    "pie",
    "bc",
    "excess",
    "st",
    "inches",
    "noon",
    "percent",
    "by",
    "gal",
    "kmh",
    "c",
    "acre",
    "rise",
    "a . m",
    "th",
    "π r 2",
    "sq",
    "mark",
    "l",
    "toy",
    "coin",
    "sq . m",
    "gallon",
    "° f",
    "profit",
    "minw",
    "yr",
    "women",
    "feet",
    "am",
    "pm",
    "hr",
    "cu cm",
    "square",
    "v â € ™",
    "are",
    "rupee",
    "rounds",
    "cubic",
    "cc",
    "mtr",
    "s",
    "ohm",
    "number",
    "kmph",
    "day",
    "hour",
    "minute",
    "min",
    "second",
    "man",
    "woman",
    "sec",
    "cube",
    "mt",
    "sq inch",
    "mp",
    "∏ cm ³",
    "hectare",
    "more",
    "sec",
    "unit",
    "cu . m",
    "cm 2",
    "rs .",
    "rs",
    "kg",
    "g",
    "month",
    "km",
    "m",
    "cm",
    "mm",
    "apple",
    "liter",
    "loss",
    "yard",
    "pure",
    "year",
    "increase",
    "decrease",
    "d",
    "less",
    "Surface",
    "litre",
    "pi sq m",
    "s .",
    "metre",
    "meter",
    "inch",
    ]
    
    for unit in unit_texts:
        # 使用正则，只匹配末尾的单位，防止误删（如 "1inch" -> "1"）
        text = re.sub(rf"{unit}\s*$", "", text, flags=re.IGNORECASE)

    # 2. 去除末尾的百分号
    text = text.replace("\\%", "").replace("%", "").replace("$", "")

    # 3. 去除变量声明 (如 "n=0" -> "0", "x=" -> "")
    text = re.sub(r"^[a-z]\s*=\s*", "", text, flags=re.IGNORECASE)

    # 4. 基础 LaTeX 清理
    text = re.sub(r"\\text\{(.+?)\}", r"\1", text)
    text = text.replace(r"\quad", "").replace(r"\,", "").replace(r"\!", "").replace(" ", "").replace(r"$", "")

    if "}" in text and "{" not in text:
        text = text.split("}")[0]
    
    return text.strip()

